[package]
name = "lavalink-rs"
version = "0.3.0-alpha"
authors = ["nitsuga5124 <nitsuga5124@gmail.com>"]
edition = "2018"
license = "MPL-2.0"
description = "Lavalink bindings for discord bot crates"
readme = "README.md"
homepage = "https://gitlab.com/nitsuga5124/lavalink-rs/"
repository =  "https://gitlab.com/nitsuga5124/lavalink-rs/"
keywords = ["lavalink", "discord", "serenity", "async"]
categories = ["multimedia"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3"
serde_json = "1.0"
serde-aux = "0.6"
futures = "0.3"
tracing-log = "0.1"
tokio-tls = "0.3"
http = "0.2"
typemap_rev = "0.1"

[dependencies.tokio]
version = "0.2"
features = ["full"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.reqwest]
version = "0.10"
features = ["json"]

[dependencies.async-tungstenite]
default-features = false
features = ["tokio-runtime", "tokio-tls"]
version = "0.4"

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity/"
branch = "current"
default-features = false
features=["model", "native_tls_backend"]

[dependencies.songbird]
git = "https://github.com/serenity-rs/songbird/"
branch = "current"
default-features = false
features = ["serenity-native", "gateway"]

[[example]]
name = "basic_play"

[[example]]
name = "basic_queue"

[dev-dependencies.tokio]
version = "0.2"
features = ["full"]

[dev-dependencies.serenity]
git = "https://github.com/serenity-rs/serenity/"
branch = "current"
default-features = false
features = ["client", "cache", "standard_framework", "voice", "default_native_tls"]

[dev-dependencies.songbird]
git = "https://github.com/serenity-rs/songbird/"
branch = "current"
default-features = false
features = ["serenity-native", "gateway"]
